/**
 * Merlin CPQ
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ServiceLinkResponse } from './serviceLinkResponse';
import { ClientLinkResponse } from './clientLinkResponse';


/**
 * Response object for Merlin Client and Service Urls
 */
export interface ConnectedSystemsResponse { 
    success?: boolean;
    clients?: Array<ClientLinkResponse>;
    services?: Array<ServiceLinkResponse>;
}

